### PR TITLE
style: making the code less complex in the fps_counter

### PR DESCRIPTION
**Pull request by lnpotter**
* Clarified the conditions under which frame rate falling is allowed, making the system more predictable and easier to debug;
* Simplified the decision structure to return true immediately in scenarios where no drop is required, reducing nested conditions;
* I've renamed the variables to be clearer about their objectives.

### CODE REVIEW

**Review by RodrigoDornelles — APPROVED** [review]
LGTM

**Comment by RodrigoDornelles** [comment]
> Simplified the decision structure to return true immediately in scenarios where no drop is required, reducing nested conditions;

This item does not match the PR, was there any git push left? Or can I merge anyway?

@lnpotter

**Comment by RodrigoDornelles** [comment]
@lnpotter If you are interested in other refactorings #52

**Comment by lnpotter** [comment]
> > Simplified the decision structure to return true immediately in scenarios where no drop is required, reducing nested conditions;
> 
> This item does not match the PR, was there any git push left? Or can I merge anyway?
> 
> @lnpotter

The function was adjusted to return `true` immediately if there are no frame drops `(drop_count == 0)`, which reduces the depth of nested conditions that follow this check.
```lua
-- original code
if fps_obj.drop_count == 0 then
    return true
end

if fps_obj.total + fps_obj.drop_count > fps_limit then
    fps_obj.falls = 0
    return true
end
```
```lua
-- modified code
if fps_tracker.drop_count == 0 then
    return true
end

if fps_tracker.total_fps + fps_tracker.drop_count > fps_limit then
    fps_tracker.fall_streak = 0
    return true
end
```

This simplification occurs early in the function, reducing the need for further evaluation within the same evaluation period, thus streamlining the decision path.



> @lnpotter If you are interested in other refactorings #52

I'll take a look.

**Pull request merged**
